# Generated by Django 5.0.7 on 2024-10-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
